options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [[ -z "${_PROJECT_ID}" ]]; then
          echo "ERROR: Missing required substitution _PROJECT_ID"
          exit 1
        fi
        if [[ -z "${_LOCATION}" ]]; then
          echo "ERROR: Missing required substitution _LOCATION"
          exit 1
        fi

  - name: 'gcr.io/cloud-builders/docker'
    dir: Frontend
    args: [ 'build',"--build-arg", "PROJECT_ID=${_PROJECT_ID}", '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/cloud-run-chatbot-deploy/frontend', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    dir: Frontend
    args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/cloud-run-chatbot-deploy/frontend']

  - name: hashicorp/terraform:1.6.0
    entrypoint: "sh"
    id: "terraform init"
    args: 
    - "-c"
    - |
      terraform init

  - name: hashicorp/terraform:1.6.0
    entrypoint: "sh"
    id: "Terraform Apply"
    args: 
      - "-c"
      - |
        terraform apply -var PROJECT_ID="${_PROJECT_ID}" -var LOCATION="${_LOCATION}" -auto-approve

timeout: 1800s